name:                uniprot-kb
version:             0.1.0.1
github:              "biocad/uniprot-kb"
license:             BSD3
author:              "Pavel Yakovlev"
maintainer:          "pavel@yakovlev.me"
copyright:           "Pavel Yakovlev"
category:            Bio
synopsis:            UniProt-KB format parser
description:         Specification implementation of https://web.expasy.org/docs/userman.html

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- text >= 0.2 && < 1.3
- attoparsec >= 0.10 && < 0.14

library:
  source-dirs: src

tests:
  uniprot-kb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniprot-kb
    - QuickCheck >= 2.9 && < 2.12
    - hspec >= 2.4.1 && < 2.6
    - neat-interpolation >= 0.3
    - attoparsec
